### ISSUE TITLE
Does not compile, EXAMPLES/../usb2lin06.hpp:9:10: fatal error: 'libusb/libusb.h' file not found

### ISSUE THREAD

**Issue by jfossi** [ranma1988/usb2lin06-HID-in-linux-for-LINAK-Desk-Control-Cable#1]
Can you help , I try to install libusb. but still no luck,

Thanks.

**Comment by UrbanskiDawid** [comment]
Hi,

Yes I would love to help :)

_option 1:_
did you try:
_$ sudo apt-get install libusb-1.0-0-dev_
and compile using:

_$ make all_

_option 2:_
there is KERNEL_MODULE
https://github.com/ranma1988/usb2lin06-HID-in-linux-for-LINAK-Desk-Control-Cable/tree/master/KERNEL_MODULE
folder
which does not use libusb at all, if you are breave enough you can use it.

please let me know if this solves your problem.
BR,
Dawid

2015-10-27 22:16 GMT+01:00 jfossi notifications@github.com:

**Comment by jfossi** [comment]
Thanks , for the response, i forget to mention i was in a mac.

Thanks
