### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by greyltc** [ranma1988/usb2lin06-HID-in-linux-for-LINAK-Desk-Control-Cable#12]
Hi, thanks for the cool project!
What license goes with this repo?

**Comment by UrbanskiDawid** [comment]
thanks,
MIT license,
please feel free to use it and if possible please mention me in credits:)

note:
I also love receiving pictures/description of products using my source.

best regards
Dawid Urbański

**Comment by greyltc** [comment]
Thanks!
I'm using this project to control the height of an experimental setup in one of our labs. Our group does solar cell research: https://www.physics.ox.ac.uk/research/group/photovoltaic-and-optoelectronic-device-group

I just packaged this in the Arch Linux user repository to make it a bit easier for me to use:
https://aur.archlinux.org/packages/linak-usb-desk-control-git/
and I didn't know what license to attach to the package, now I do! :-)
