### ISSUE TITLE
Connector Pins

### ISSUE THREAD

**Issue by tillsteinbach** [ranma1988/usb2lin06-HID-in-linux-for-LINAK-Desk-Control-Cable#2]
Hi,
did you find out the pin assignment of the connector? I would love to use an Arduino to interface my table. If you already found the Pins responsible for LIN-Bus, I would be happy for any information that you have.

**Comment by UrbanskiDawid** [comment]
I think you can easily control your table with arduino (I'm currently experimenting with it)  please refer to 
https://github.com/ranma1988/usb2lin06-HID-in-linux-for-LINAK-Desk-Control-Cable/tree/master/PHOTOS/DP-003-buttonsBoard
 see?  Just a buttons connected directly to cable.

**Comment by tillsteinbach** [comment]
Yes, but I would like to use the LIN bus as I would also like to read the current position. So if the pin is currently unknown I will carry the scope from work to find the right pin

**Comment by UrbanskiDawid** [comment]
In this case you have to  continue with https://github.com/ranma1988/usb2lin06-HID-in-linux-for-LINAK-Desk-Control-Cable/tree/master/PHOTOS/DP-003-buttonsBoard
And no there was no work done on hardware side.  (one guy tried it but after a wile has given up)  so you might be the first one.  Good luck. Please share your findings on hardware side!

**Comment by tillsteinbach** [comment]
I will try to find out what is possible, but I might need to buy a USB2LIN06 to sniff the communication on the bus.

**Comment by wridgers** [comment]
@tillsteinbach Did you have any luck figuring it out?

I have an Arduino, ultrasonic sensor, and relays controlling the desk for now. It works, but implementing the protocol would be a cleaner solution.

**Comment by backbone10** [comment]
Hi, may I kindly ask if there was progress in decoding and building the USB cable? The prize is still horrible.. THX bb10
