### ISSUE TITLE
Anyone has an idea where to buy a USB2LIN06?

### ISSUE THREAD

**Issue by tillsteinbach** [ranma1988/usb2lin06-HID-in-linux-for-LINAK-Desk-Control-Cable#4]
Anyone has an idea where to buy the USB2LIN06?

**Comment by UrbanskiDawid** [comment]
https://sit-stand.com/linak-accessories/86-usb-cable.html

**Comment by aesterling** [comment]
I purchased mine from myupdesk.com in the US. I paid $59.00 and shipping was free, but the item is not listed on their website. I had to call UpDesk to place my order (XXX) XXX-XXXX.

**Comment by omartijn** [comment]
I really wonder whether we actually need this expensive cable. It's probably some serial port communication, does anybody have any idea?

**Comment by naikrovek** [comment]
it's a modified LIN protocol, and the cable has a microcontroller in it that translates USB from the PC to the modified LIN protocol that the actual desk controller communicates in.  I don't have documentation on the protocol or how it's modified.  You'll have to do that legwork yourself.
