### ISSUE TITLE
Linak Bluetooth adapter or DPG Controller

### ISSUE THREAD

**Issue by jfossi** [ranma1988/usb2lin06-HID-in-linux-for-LINAK-Desk-Control-Cable#7]
Hi, 

Any Plans to make the program work with Bluetooth.?

**Comment by UrbanskiDawid** [comment]
Bluetooth? are you referring to [linak.com - bluetooth-adapter-desk](https://www.linak.com/products/accessories/bluetooth-adapter-desk/) ?

**Comment by jfossi** [comment]
yes or the new dpg
https://www.linak.com/products/controls/dpg/

**Comment by UrbanskiDawid** [comment]
I could possibly do it but I don't have this device to play with it. any propositions?
